DROP TABLE IF EXISTS account;

CREATE TABLE account (
  user_id VARCHAR(250) UNIQUE PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);